# backend/tancho/config/config.yml

fastapi:
  debug: true

databases:
  default:
    ENGINE: 'mongodb'
    DRIVER: 'motor'
    NAME: 'tancho_db'
    USER: 'tancho_user'
    PASSWORD: '4dm1n4dm1n'
    HOST: 'mongo'
    PORT: 27017
